### ISSUE TITLE
python viertual env don't copy the Data folder

### ISSUE THREAD

**Issue by Ivan-Castro** [lenarother/moderna#63]
When I installed Moderna using pip in a python virtualenv, and I tried to import the package, I got a 'File not found' error. The problem was that the Data folder was not copied to the site-packages/moderna. The solution was easy: copy/past manually the Data folder to site-packages/moderna. But anyway, it was an error that should not have happend.

**Comment by cosi1** [comment]
Hello and thanks for your interest in ModeRNA!

The new version is in the early-alpha stage at the moment and some (essential) features are still missing. I agree, though, that this shouldn't have happened; we'll try to fix it as soon as possible.

Sorry for the inconvenience,
Paweł

**Comment by Ivan-Castro** [comment]
No problem ;)

I just wanted notify you. You are doing a great package.
